[local]
localhost

[mongodb]
localhost

[catalogue]
localhost

[redis]
localhost

[user]
localhost

[cart]
localhost

[mysql]
localhost

[shipping]
localhost

[rabbitmq]
localhost

[payment]
localhost

[frontend]
localhost

[all:vars]
MONGODB_HOST=mongodb-"{{env }}".daws88-s.online
CATALOGUE_HOST=catalogue-"{{env }}".daws88-s.online
REDIS_HOST=redis-"{{env }}".daws88-s.online
USER_HOST=user-"{{env }}".daws88-s.online
CART_HOST=cart-"{{env }}".daws88-s.online
MYSQL_HOST=mysql-"{{env }}".daws88-s.online
SHIPPING_HOST=shipping-"{{env }}".daws88-s.online
RABBITMQ_HOST=rabbitmq-"{{env }}".daws88-s.online
PAYMENT_HOST=payment-"{{env }}".daws88-s.online

